version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./storage:/application/storage
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
